### ISSUE TITLE
I wanna run this thing on a mac

### ISSUE THREAD

**Issue by jdolitsky** [chainguard-dev/apko#111]
Idea: maintain a [Lima](https://github.com/lima-vm/lima) config file which allows you mount a workspace containing YAMLs into a QEMU alpine environment with the most recent release of apko preinstalled. There's an [example Alpine config ](https://github.com/lima-vm/lima/blob/master/examples/alpine.yaml)we can build upon.

Any better alternatives to this?

**Comment by kaniini** [comment]
Seems like a good idea!
