### ISSUE TITLE
Show `config.yaml` in README

### ISSUE THREAD

**Issue by steren** [chainguard-dev/apko#166]
I'd like to see what this tool is all about, so giving an example `config.yaml` alongside the `apko build config.yaml tag output.tar` in the README is probably the first step for me to better understand it.

**Comment by steren** [comment]
(and yes, I have found the [examples](https://github.com/chainguard-dev/apko/tree/main/examples) directory, it's just it required me to read text, when I was actually looking for some kind of hello world config.yaml that would convey the tool's value)

**Comment by kaniini** [comment]
Assigning @amouat since he's working on making our docs better already.

**Comment by amouat** [comment]
Yup, fully agree with this issue and I'm on it.

**Comment by kaniini** [comment]
Closed by #169.
