### ISSUE TITLE
`entrypoint.command` has inconsistent documentation

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/apko#170]
I noticed the example uses:
```
entrypoint:
  command: ...
```

However, [here](https://github.com/chainguard-dev/apko/blob/da97502c92ac2aaef585aae80654ec2952cba434/docs/apko_file.md#entrypoint-top-level-element) is talks about the child element `cmd`.  I suspect the latter should just be `command`.

**Comment by amouat** [comment]
Yeah, I think that's just a mistake on my part from looking at the code.
