### ISSUE TITLE
`entrypoint.command` unexpectedly wraps things in `/bin/sh -c`

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/apko#171]
If I try to set the entrypoint of the github.com/distroless/git image to `/bin/git` with:

```yaml
entrypoint:
  command: /bin/git
```

I get:
```json
    "Entrypoint": [
      "/bin/sh",
      "-c",
      "/bin/git"
    ],
```

I thought this might be the string vs. list nonsense inherited from Docker, but trying to make it a list (somewhat expectedly) results in:

```
2022/04/10 19:39:07 loading config file: .apko.yaml
Error: failed to load image configuration: failed to parse image configuration: yaml: unmarshal errors:
  line 13: cannot unmarshal !!seq into string
2022/04/10 19:39:07 error during command execution: failed to load image configuration: failed to parse image configuration: yaml: unmarshal errors:
  line 13: cannot unmarshal !!seq into string
```

I can believe I'm holding things wrong, but I guess I'd expect the default behavior to not assume the existence of a shell given our overarching goals with `apko`.

**Comment by kaniini** [comment]
Yeah this is something @puerco was planning to change, e.g. `entrypoint.command` vs `entrypoint.shell-command`
