### ISSUE TITLE
Support empty Entrypoint

### ISSUE THREAD

**Issue by amouat** [chainguard-dev/apko#177]
With the official Docker alpine image, I can do this:

```
❯ docker run alpine:latest echo foo
foo
```

But with our current images, this happens:

```
❯ docker run alpine:base echo foo
/bin/sh: can't open 'echo': No such file or directory
```

I'm not 100% sure what's happening, I guess it's something to do with quoting. Our entrypoint is set to `/bin/sh -l`

Now, if we look at the [Dockerfile for the alpine official image](https://github.com/alpinelinux/docker-alpine/blob/fc965e3222f368bea8e07c1c1da70b6928281a76/x86_64/Dockerfile), it doesn't set the entrypoint at all! It seems this triggers some default behaviour in Docker, which effectively runs `/bin/sh -c`, with quoting handled correctly.

In our code, we[ set the entrypoint manually if it's not specified](https://github.com/chainguard-dev/apko/blob/main/pkg/build/oci/oci.go#L118), so leaving out the entrypoint does not have the same effect. I could actually force it with the following yaml:

```
entrypoint:
    command: " "
```

And this gives us an alpine image that works in the same way as the official image:

```
❯ docker run alpine:base echo foo
foo
```

So I guess this is a long winded way of saying we should have some way to allow the entrypoint to be empty. 

I'm happy to do a PR for that, but I'm also wondering if we need to think about the syntax. I find it a bit confusing, as "command" sets the image's entrypoint and not "cmd".

**Comment by kaniini** [comment]
Just make it so that if entrypoint is unspecified that it doesn’t set one.

**Comment by amouat** [comment]
I did that, but the problem with my approach is that just running the image now does this:

```
docker run alpine:base
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```

I'd like to solve it by adding support for setting cmd, but from reading the code I'm wondering if we were intentionally avoiding using cmd?
