### ISSUE TITLE
create --load flag for build cmd

### ISSUE THREAD

**Issue by developer-guy** [chainguard-dev/apko#193]
In the meantime, people need to run additional docker command (load) in order to load image to docker after building it with apko, so, it would be better to add another flag like --load for build command to provide the same experience in a single command like the following:

```
$ apko build --load ..
```

WDYT @kaniini?

**Comment by developer-guy** [comment]
I'm willing to do this, so, feel free to assign it to me 🙋🏻‍♂️

**Comment by imjasonh** [comment]
This came up in https://github.com/distroless/static/pull/9

Do we want `apko publish apko.local` to signal a local image? This should be pretty easy after we decide that.

**Comment by kaniini** [comment]
Solved by `apko publish --local`!
