### ISSUE TITLE
apko docker image entrypoint is maybe a little weird?

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#22]
While working on GitHub actions integration for a demo, I noticed:

```
localhost:~/actions/apko-build$ docker run ghcr.io/chainguard-dev/apko:v0.1 
Error: unknown command "/bin/sh" for "apko"
Run 'apko --help' for usage.
2022/02/28 23:03:27 error during command execution: unknown command "/bin/sh" for "apko"
```

@cpanato @mattmoor what do you think?  are we missing something with `ko`?

**Comment by mattmoor** [comment]
I wonder if this is the shell vs. exec problem?

https://www.ctl.io/developers/blog/post/dockerfile-entrypoint-vs-cmd/

**Comment by mattmoor** [comment]
This definitely looks like a `ko` bug, I'm guessing related to `Cmd` override semantics from the base image.

![image](https://user-images.githubusercontent.com/2442466/156081365-c8a95fad-2bc1-43f3-ae77-ca516bcad98a.png)

cc @imjasonh @jonjohnsonjr

**Comment by jonjohnsonjr** [comment]
Yeah we should do [this](https://github.com/google/go-containerregistry/blob/5d4fcd480bf356afc3e784e7a687f93953fc7e9f/cmd/crane/cmd/mutate.go#L95-L99) [here](https://github.com/google/ko/blob/56e14a14181798c626fbf94d8f4ff588f03ec176/pkg/build/gobuild.go#L778).

**Comment by mattmoor** [comment]
I think we want one more line here to clear `Cmd`: https://github.com/google/ko/blob/d48a62134c73adee7f67304e175d8e3559fbb031/pkg/build/gobuild.go#L777-L778

WDYT?

**Comment by mattmoor** [comment]
@jonjohnsonjr wrong project 🤣

**Comment by mattmoor** [comment]
We want your `nil` line where I linked.

**Comment by mattmoor** [comment]
maybe that's what you meant?

**Comment by jonjohnsonjr** [comment]
We linked to the same line - `this` and `here` are different links.

**Comment by kaniini** [comment]
...we probably also want this in `apko`!

**Comment by mattmoor** [comment]
apko doesn't have a base image... 🤔 

Our problem is we clone the base image's config and tweak it.

**Comment by kaniini** [comment]
true, but apko doesn't explicitly null `Cmd`.  at any rate, if the next `ko` release fixes it, I think we can close this for now
