### ISSUE TITLE
Set org.opencontainers.image.source if we know it

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#231]
We should set the `org.opencontainers.image.source` annotation if we know it.  Should be possible to do it by deducing a `vcs-url` from the `origin` upstream if `.git` is present.

**Comment by kaniini** [comment]
(we should also do this in a way where it can be included into `ko`, `kaniko`, etc)

**Comment by dlorenc** [comment]
+1. go set a good precendent here by including repo information in binaries by default.

**Comment by Histalek** [comment]
Be aware that this might leak secrets of some build systems.
E.g. in this specific case the produced label contains the `gitlab-ci-token` if you are building an image with apko through gitlab-ci/gitlab-runner.

The resulting (redacted) label looks like this:
```
 "org.opencontainers.image.source": "https://gitlab-ci-token:[REDACTED]@gitlab.example.com/<namespace>/<project>.git"
```

According to the GitLab Docs [2]:
> The CI job token becomes invalid if the job is no longer running, has been erased, or if the project is in the process of being deleted.

Which decreases the risk of someone actually abusing this, but
- other build-systems might handle this differently
- this isn't exactly nice for the reader, as they have to disregard a third or so of the url

Maybe the url can be sanitized in some way to prevent this.

[1] https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html#troubleshooting

**Comment by kaniini** [comment]
Yeah I have a patch landing shortly to sanitize the URLs so they only reflect the public URI.  Also an option to disable setting the VCS URL too.
