### ISSUE TITLE
Take care of s6 directory creation

### ISSUE THREAD

**Issue by amouat** [chainguard-dev/apko#240]
If it's being installed, we should make sure s6 can run without changes to the yaml. At the moment I'm getting:

```
$ docker run ghcr.io/distroless/nginx@sha256:21b4eaf7e0dc0650d3f8372a9f49fe7eb767331ebd033a914848e43ef17e54c4
s6-svscan: fatal: unable to mkdir .s6-svscan: Permission denied
```

**Comment by dansiviter** [comment]
Just hit this issue. Is there a workaround? I can't get rootless Nginx to work.

**Comment by amouat** [comment]
Yeah, there is. We can just create the dir in the yaml. I'm just going for lunch but will link an example in an hour or so.

**Comment by amouat** [comment]
This is actually proving more difficult than I thought 😒

**Comment by kaniini** [comment]
I have some ideas on how to fix this, will open a PR shortly.

**Comment by dansiviter** [comment]
FYI As a workaround, I'm just using:

```yaml
entrypoint:
  command: nginx -g "daemon off;"
```
 ...until the `service-bundle`/s6 stuff is fixed. It seems to work fine using rootless too.

**Comment by kaniini** [comment]
I think this issue with the s6 supervision tree is only specific to rootless variant, so we just need to ensure the /sv dir has appropriate permissions.
