### ISSUE TITLE
Unable to run tests inside apko without additional installations

### ISSUE THREAD

**Issue by jspeed-meyers** [chainguard-dev/apko#255]
I followed the instructions at [CONTRIBUTING.md ](https://github.com/chainguard-dev/apko/blob/main/CONTRIBUTING.md) and ran into a problem when running the tests.

```
[apko] ❯ go test ./...
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
FAIL	chainguard.dev/apko/pkg/apk [build failed]
FAIL	chainguard.dev/apko/pkg/build [build failed]
FAIL	chainguard.dev/apko/pkg/build/types [build failed]
FAIL	chainguard.dev/apko/pkg/exec [build failed]
FAIL	chainguard.dev/apko/pkg/passwd [build failed]
FAIL	chainguard.dev/apko/pkg/sbom [build failed]
FAIL	chainguard.dev/apko/pkg/sbom/generator/spdx [build failed]
FAIL	chainguard.dev/apko/pkg/tarball [build failed]
```

Was I supposed to do something differently to avoid this problem? I installed `golangci-lint` as requested by CONTRIBUTING via this command (found [here](https://golangci-lint.run/usage/install/)):

```wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.45.2```

I'll assume this is user error, but if not, perhaps the documentation needs updating or the development environment should be tweaked? I'm glad to put in a PR if there is a preferred course of action and a little bit of guidance.

**Comment by kaniini** [comment]
Needs `build-base` in the apko devenv image I think.

**Comment by panekj** [comment]
Can't you just disable CGO with `CGO_ENABLED=0`?

**Comment by jspeed-meyers** [comment]
@kaniini, I added this line of code to `examples/apko-devenv.yaml` under `packages:`:

`    - build-base` 

And the re-ran `./hack/make-devenv.sh`.

I checked I had `gcc` installed:

```
[apko] ❯ apk list libgcc
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/community: No such file or directory
libgcc-11.2.1_git20220219-r2 aarch64 {gcc} (GPL-2.0-or-later LGPL-2.1-or-later) [installed]
```

Then I ran 

`go test ./...`

and got this this:

```
LOTS OF GO IMPORTS
...
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
FAIL	chainguard.dev/apko/pkg/apk [build failed]
FAIL	chainguard.dev/apko/pkg/build [build failed]
FAIL	chainguard.dev/apko/pkg/build/types [build failed]
FAIL	chainguard.dev/apko/pkg/exec [build failed]
FAIL	chainguard.dev/apko/pkg/passwd [build failed]
FAIL	chainguard.dev/apko/pkg/sbom [build failed]
FAIL	chainguard.dev/apko/pkg/sbom/generator/spdx [build failed]
FAIL	chainguard.dev/apko/pkg/tarball [build failed]
```

Do I need to add `gcc` to the path? What am I missing?

Also, @panekj, I ran `CGO_ENABLED=0` inside the dev environment, reran the test command, and got the same error. Did I run that command in the right place?

Thank you both for the help.

cc @amouat

**Comment by kaniini** [comment]
libgcc is not gcc, but rather the support library to run programs compiled with gcc.  `build-base`, however, pulls gcc in as a dependency.

Most likely you needed to `docker image prune` after ensuring your containers were stopped.

**Comment by jspeed-meyers** [comment]
I'm guessing this is all overcome by events given that the apko docker image is now the preferred way to run this, not the hacks script. Given that, closing. If you want a PR with the build-base package added, let me know.
