### ISSUE TITLE
Add docker installed as requirement in README (for MacOS only?)

### ISSUE THREAD

**Issue by jspeed-meyers** [chainguard-dev/apko#259]
> AFAIK yes, Docker is needed if you are using the scripts at hack/ to run the dev env, but if you are on Alpine you can probably run it directly. For wider compatibility IMO we should focus on the docker env so yeah this should definitely be added to requirements.

@erikaheidi mentioned this in now closed PR #254. Should docker installation be included in the README in the installation section a prerequisite. Is it only a prerequisite for Mac users?

Once I have an answer, I'm glad to put in a PR.

**Comment by amouat** [comment]
I added some more docs about getting started on Mac and the Docker requirement to #311, which I think closes this issue.
