### ISSUE TITLE
apko ignores specified archs in config yml

### ISSUE THREAD

**Issue by sando38** [chainguard-dev/apko#290]
I tried building a simple alpine base image with apko from the examples, however, apko seems to ignore the specified archs in the yml config file. Here is the log:

```
2022/07/12 18:47:22 WARNING: ignoring archs in config, only building for current arch (arm64)
```

Archs are defined this way:

```
archs:
  - amd64
  - 386
```

Machine I am building with:

ArchLinux with qemu v7.0.0 installed. 
I am running apko with `./hack/make-devenv.sh`. Building a single image e.g. with `--build-arch arm64` works fine as well.
Docker buildx for multiarch works fine, too.

Am I missing something, any hint would be appreciated.

Thanks and have a great day!

**Comment by kaniini** [comment]
The `apko build` action only builds a locally importable image.  Multiarch mode requires `apko publish`.  This should be more clearly documented, I guess.

**Comment by sando38** [comment]
Ahh alright! This makes sense!

> This should be more clearly documented, I guess.

I agree.

Thanks for the great tool.
