### ISSUE TITLE
arm64: failed to install busybox symlinks

### ISSUE THREAD

**Issue by gliwka** [chainguard-dev/apko#291]
I'm trying to use apko to build a container for amd64 and arm64 using the `distroless/actions/apko-publish` action.

It seems to build the amd64 image just fine, but fails building the arm64 image during the following step:

```
Error: failed to build layer image for "arm64": failed to install busybox symlinks: failed to install busybox symlinks: exit status 126
[179](https://github.com/microrun/toolchain/runs/7308867609?check_suite_focus=true#step:4:180)
2022/07/12 19:31:05 error during command execution: failed to build layer image for "arm64": failed to install busybox symlinks: failed to install busybox symlinks: exit status 126
```

The action run:
https://github.com/microrun/toolchain/runs/7308867609?check_suite_focus=true#step:4:179

Test yaml to build: 
https://github.com/microrun/toolchain/blob/6de11cbdb3bcc4d7eb1e1d9bda90f0a75b49abda/c-cplusplus.yaml

Thanks for building apko, finally a nice declarative way to build up-to-date images that only change if there's something new! 🥳

**Comment by kaniini** [comment]
You need to use the `docker/setup-binfmt` action first if you're doing multiarch on GHA.

**Comment by gliwka** [comment]
@kaniini Thank you, totally missed that.

Using docker/setup-qemu-action fixed it.
