### ISSUE TITLE
Set up some actions for presubmit validation

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/apko#3]
We have loads of these in our mono repo, and many of these are based on workflows we've forked repeatedly over the years.

I'm tempted to set up `chainguard-dev/actions` where we can stuff reusable workflows with `workflow_call` that we can recycle across our various repos over time.

cc @n3wscott @k4leung4

**Comment by cpanato** [comment]
hum, sounds a nice idea

**Comment by k4leung4** [comment]
+1

it would make it easier if we are looking to reuse actions/workflows outside of mono.

**Comment by cpanato** [comment]
@mattmoor if you create the repo, i can submit PRs to add initial jobs

**Comment by cpanato** [comment]
made a quick one in my own github

the shared job: https://github.com/cpanato/actions-reusable-test/blob/main/.github/workflows/build-test-go.yml
running in another repo: https://github.com/cpanato/testing-ci-providers/actions/runs/1874993811

**Comment by mattmoor** [comment]
I am starting with some composite workflows here to replace some of the ones we've been copying around from Knative forever: https://github.com/chainguard-dev/actions

**Comment by cpanato** [comment]
super cool

**Comment by kaniini** [comment]
We're now using chainguard-dev/actions integration, so I think this can be closed.  Reopen if there's more stuff we want to add.
