### ISSUE TITLE
Consider moving ./cmd/apko/main.go to ./main.go

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/apko#31]
`ko` used to be in `./cmd/ko`, but @n3wscott correctly pointed out that makes the `go install` instructions needlessly long and stutttery, so we moved it to `./main.go` and made `./cmd/ko/main.go` log a warning then call the usual cobra root entrypoint.

See https://github.com/google/ko/pull/257 for the whole saga.

If you think `apko` will follow a similar path, it might be worth moving it up now, while there are few enough users.

If this sgty I can send a PR.

**Comment by kaniini** [comment]
Go for it!
