### ISSUE TITLE
Essentially only works on alpine due to keychain requirements

### ISSUE THREAD

**Issue by 06kellyjac** [chainguard-dev/apko#310]
I've not managed to get apko to work on a non-alpine system reliably. Some guidance on how to populate the keychain, or if apko could do that well that'd be good.

And ideally the keychain could go into `/tmp` or `XDG_DATA_HOME` or something rather than `/etc/apk/keys` and `/usr/share/apk/keys`

https://github.com/chainguard-dev/apko/blob/main/pkg/apk/apk.go#L37-L40

Maybe `--keyring-append` & `--repository-append` would also help with that 2nd part

**Comment by kaniini** [comment]
You can use https URIs for keys that you want to use.

**Comment by kaniini** [comment]
This was solved in apko 0.7.0.  Alpine keys, if needed, will be downloaded from Alpine automatically.
