### ISSUE TITLE
ability to generate an image with multiple tags

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#34]
It'd be nice to support, e.g.

`apko build foo.yaml foo/bar/baz:v1.3 foo/bar/baz:latest`

**Comment by imjasonh** [comment]
Not that you have to follow `ko`'s precedent, but `ko` does this with `--tags=v1.3,latest` (or `--tags=v1.3 --tags=latest`).

This would be `apko build foo.yaml foo/bar/baz --tags=v1.3 --tags=latest`

**Comment by kaniini** [comment]
apko already does it the way i describe, just with a single tag
