### ISSUE TITLE
Allow configuring OCI annotations

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/apko#352]
https://github.com/opencontainers/image-spec/blob/main/annotations.md

Let users configured annotations in apko.yaml

We could also do something smart with `image.source`, `image.revision` and `image.version` if we can detect we're running from a clean Git commit, but those smarts should probably be opt-in.

**Comment by imjasonh** [comment]
Oh most of this is already done in https://github.com/chainguard-dev/apko/pull/296, it's just not documented.

Should we do the smart thing and try to detect source URL/revision/version?

**Comment by imjasonh** [comment]
There's already `--vcs` (default true) which sets the source URL: https://github.com/chainguard-dev/apko/blob/868f0dc23e721039f9669b56d01ea4b897f2fb24/pkg/build/oci/oci.go#L112

**Comment by JTarasovic** [comment]
It also seems like `publish` doesn't currently actually add the annotations from the config file.

I set up a repro with a fork of chainguard-images/static at JTarasovic/static:
https://github.com/chainguard-images/static/compare/89993cb...JTarasovic:static:main

And published using the action to ghcr: https://github.com/JTarasovic/static/actions/runs/3147616207/jobs/5117290180

Without luck
```
regctl image manifest ghcr.io/jtarasovic/static:latest
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:59c6fed2d149b743da3c62915307ada35752233b545f902260dea45cf46c56f2",
    "size": 509
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
      "digest": "sha256:daad3cbec1232c756efc4df8dfb471fab62a7f9f38b7fb495ca403b2f163b43e",
      "size": 489220
    }
  ],
  "annotations": {
    "org.opencontainers.image.source": "gh:chainguard-images/static@065bb0cba7b326a3258eeab84585195cb46cd674"
  }
}
```

If there's anything I can do to help, don't hesitate to let me know.

**Comment by imjasonh** [comment]
https://github.com/chainguard-dev/apko/pull/353 should fix the issue. There's a question in the PR about how to handle the vcsurl, if there's any pushback there we can at least merge the annotations support.

**Comment by JTarasovic** [comment]
Nice! I thought it might but couldn't tell for sure with a brief review.

Not sure if it'd be appropriate for that PR but it may make sense to have `VCSUrl` be a struct instead of joining the strings together and cutting them back apart. :shrug: No pushback here, though :wink:
