### ISSUE TITLE
Question, how to pass credentials to publish command

### ISSUE THREAD

**Issue by LarsKrogJensen** [chainguard-dev/apko#377]
trying to use apko to build and publish an image to a repo, but fails as it seems it cannot authenticate with repo.

Any way to pass credentials with the apko publish?

**Comment by imjasonh** [comment]
apko uses [go-containerregistry's `DefaultKeychain`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/authn#DefaultKeychain) to pick up any credentials configured in the Docker config (typically ~/.docker/config.json`), which is also where credentials are stored when you run `apko login` (or `docker login`)

If you can share some more information about your environment, what registry you're trying to auth to, etc., I might be able to help more.

**Comment by LarsKrogJensen** [comment]
I am running a jenkins pipeline (on k8s) and is using harbor as image repo, credentials secret is mounted as a volume so should be

I wan't aware there was a apko login, so will try that.

As a work around I used crane to publish, but would rather not have another container if I can avoid it

**Comment by imjasonh** [comment]
That's the SBOM for the image, pushed as a separate manifest. To fetch the SBOM, you can use:

[`cosign download sbom [YOUR/IMAGE]@sha256:f3d4a83eb926eb7ef2798f721667a1cde658617a4c52196c76bfb6e885b137c5`](https://github.com/sigstore/cosign/blob/main/doc/cosign_download_sbom.md)

You can disable this with `--sbom=false`.
