### ISSUE TITLE
Glibc builds not reproducible

### ISSUE THREAD

**Issue by amouat** [chainguard-dev/apko#387]
At the moment running a build twice is resulting in different binaries:

```
$ docker run --rm -v "${PWD}":/work \
    cgr.dev/chainguard/apko build --sbom=false --build-date "1970-01-01T00:00:00Z" apko-glibc.yaml \
    busybox-local output.tar  \
    --build-arch amd64
...
$ shasum -a 256 output.tar
4bb709225450e0e673470141989de0b113ac279ca4c056f1242a9aa70a41a4e6  output.tar

```

Repeat and I get:

```
shasum -a 256 output.tar
080dc7af856092ea2673577efc05c744b204db1fba8ace734efd2ce28b173df4  output.tar
```

Size remains the same. There was speculation that this is due to ordering changing in `/var/cache/ldconfig/aux-cache`.

It would be worthwhile adding a test that checks for reproducibility with a non-trivial image.

**Comment by kaniini** [comment]
This was resolved in apko 0.7.0, we discovered we do not actually need the ld.so cache.
