### ISSUE TITLE
apko uses native golang tooling instead of shelling out apk-tools

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#389]
Using the apk support we are adding to [alpine-go](https://gitlab.alpinelinux.org/alpine/go), we should replace our use of `apk-tools` inside apko.

**Comment by puerco** [comment]
@jdolitsky or @kaniini can we break this into smaller chunks to start completing it? I don't have a clear picture in my mind of what still needs to be done.

**Comment by jdolitsky** [comment]
FYI - Avi was looking into some of this this week

**Comment by puerco** [comment]
I started to look into this one too, as discussed earlier this week, I figured we need to implement the following in go to get rid of the apk-tools dependency:

1. The apk filesystem/db initialization
1. A port of the resolver algorithm
1. apk packages install/remove/update
1. apkdb update

I opened https://github.com/chainguard-dev/apko/pull/412 to handle # 1 above but I'll defer this work to not duplicate Avi's work.

**Comment by deitch** [comment]
Actually, the implementation is mostly done. So are most of the tests (with each test, discovering a new thing that I did not do quite right).

**Comment by patflynn** [comment]
very close. apko running on @jdolitsky 's mac.

**Comment by patflynn** [comment]
@kaniini

**Comment by jdolitsky** [comment]
closing as done.

New issues:
- https://github.com/chainguard-dev/apko/issues/469
- https://github.com/chainguard-dev/apko/issues/470
