### ISSUE TITLE
SBOMs listing wolfi packages have 'alpine' in their purl namespace 

### ISSUE THREAD

**Issue by puerco** [chainguard-dev/apko#399]
Packages in the SBOMs have `alpine` in the purl namespace, even when images are using wolfi packages.

```
       referenceLocator": "pkg:apk/alpine/libssl3@3.0.5-r3?arch=x86_64",
```

**Comment by imjasonh** [comment]
`ReadReleaseData`, which reads `/etc/os-release` in the image and parses it to set the actual OS name/version/etc, is never called outside of tests: https://github.com/search?q=repo%3Achainguard-dev%2Fapko%20readreleasedata&type=code

I think we should change the default OS etc to `"unknown"` so it's clearer they're not based on anything, and figure out where and how to call `ReadReleaseData` so the actual os-release is consulted.
