### ISSUE TITLE
Warn users when producing an image with an unknown distro

### ISSUE THREAD

**Issue by luhring** [chainguard-dev/apko#447]
Problem: Today, when apko builds an image, if none of the packages it adds to the image include an `/etc/os-release` file, the image will end up with an `/etc/os-release` file that gets created on-the-fly, which looks like this:

```text
ID=unknown
NAME="apko-generated image"
PRETTY_NAME="apko-generated image"
VERSION_ID=unknown
HOME_URL="https://github.com/chainguard-dev/apko"
```

This can be problematic. In particular, if someone runs a vulnerability scanner on the image, the scanner will not be able to correctly identify the distro, and thus the scanner won't be able to locate the appropriate advisory/fix data source to use during the scan — which means the scan results will be invalid.

In most cases, apko users probably don't _intend_ to have an unidentified distro like this. It's more likely that they just didn't realize how to add a proper distro `/etc/os-release` file, which today is done by including a package in the config file that contains an `/etc/os-release` file.

Therefore, apko should check to see if any package has added an `/etc/os-release` file and ensure the user sees a warning about the fact that the distro won't be identifiable and how that can lead to problems.

**Comment by tuananh** [comment]
i'm curious to why would a package want to do that?

**Comment by mritunjaysharma394** [comment]
Hi @luhring, seems to be a good issue to begin with contribution to apko, can I pick this? I

**Comment by luhring** [comment]
Thanks for the PR @mritunjaysharma394! Hopefully we can get that merged soon 🤞
