### ISSUE TITLE
Error "unsupported protocol scheme" while building

### ISSUE THREAD

**Issue by nmeisenzahl** [chainguard-dev/apko#485]
Hi all, 

I have an issue while building an apk with local packages. I'm getting the following error:
```
Error: failed to build layer image: initializing apk: failed to fixate apk world: error getting repository indexes: unable to get repository index at @local/aarch64/APKINDEX.tar.gz: Get "@local/aarch64/APKINDEX.tar.gz": unsupported protocol scheme ""
2023/02/02 17:51:20 error during command execution: failed to build layer image: initializing apk: failed to fixate apk world: error getting repository indexes: unable to get repository index at @local/aarch64/APKINDEX.tar.gz: Get "@local/aarch64/APKINDEX.tar.gz": unsupported protocol scheme ""
Error: exit status 1
```

My config:

```yaml
  repositories:
    - https://packages.wolfi.dev/os
    - '@local /work/packages'
  packages:
    - busybox
    - ca-certificates-bundle
    - nghttp2
    - nodejs
    - wolfi-baselayout
    - hello-app@local
```

My build command:

```
nerdctl run --privileged --rm -it -v ${PWD}:/work -w /work --entrypoint /usr/bin/apko cgr.dev/chainguard/sdk build --debug --build-arch aarch64 apko.yaml hello-app hello-app.tar
```

My previous melange build finished successfully. The local packages folder contains the index file (`packages/aarch64/APKINDEX.tar.gz`) as well as the apk.

I'm getting the same error when including `--repository-append /packages` into the build command.

Any tip is welcome! Thanks Nico

**Comment by nmeisenzahl** [comment]
Ok, it looks like this is related to the used version. I'm getting the above error with tag `latest-20230119` but `latest-20230118` and older are working fine.

**Comment by kaniini** [comment]
This is likely due to the native golang implementation of apk.

**Comment by kaniini** [comment]
hey @deitch can you look at this one?

**Comment by deitch** [comment]
Yup

**Comment by deitch** [comment]
Yeah, it definitely is from that. There was an assumption that everything in `repositories` would be either a valid URL or a file path. Clearly, it is not.

Is the rule, as long as it starts with `@local`, then space, followed by a local file path? And what should be inside that local file path? Is it the same layout as at the URL, i.e. we can expect to see `<path>/<arch>/APKINDEX.tar.gz`, and each `.apk` file is similarly placed, as if it were on a Web server? Or is it something else?

**Comment by nmeisenzahl** [comment]
@deitch Maybe this helps?

```
ls -lisa packages/aarch64/
total 1424
54609703    0 drwxr-xr-x  4 nico  staff     128 Feb  2 19:13 .
54609702    0 drwxr-xr-x  3 nico  staff      96 Feb  2 19:13 ..
54609705    8 -rw-r--r--  1 nico  staff     852 Feb  3 14:18 APKINDEX.tar.gz
54609704 1416 -rw-r--r--  1 nico  staff  722922 Feb  3 14:18 hello-app--r0.apk
```

**Comment by deitch** [comment]
Yup that looks the same. We will add it in.

**Comment by deitch** [comment]
@nmeisenzahl I was reading through the [description](https://wiki.alpinelinux.org/wiki/Alpine_Package_Keeper#Packages_and_Repositories) again. If you don't use pinned repositories, i.e. just put in `/work/packages`, it should work fine as is. It only matters if you need to support pinned packages.

We will add it, but if using just `/work/packages` helps you get past it for now, that would be good.

**Comment by deitch** [comment]
See #539
