### ISSUE TITLE
Error building image with s6 (nginx)

### ISSUE THREAD

**Issue by jdolitsky** [chainguard-dev/apko#497]
Some permissions related issue for an nginx build:

```
curl -LO https://raw.githubusercontent.com/chainguard-images/images/main/images/nginx/configs/latest.apko.yaml

./apko build latest.apko.yaml nginx output.tar

docker load < output.tar 

docker run --rm nginx:latest
```

Error:
```
s6-svscan: fatal: unable to mkdir .s6-svscan: Permission denied
```

And running as root, different type of error:
```
docker run --rm -u root nginx:latest
```

```
s6-supervise nginx: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise nginx (child): fatal: unable to exec run: Permission denied
```

**Comment by deitch** [comment]
Got it. The permissions on `/sv` directory in the new image are off:

```
drwxrwxrwx    1 root     root          4096 Feb 10 12:46 /sv
```

vs

```
drwxr-xr-x    3 root     root          4096 Jan  1  1970 /sv
```

Now to figure out why that is. 

This just makes the stronger case for what we wanted to do @jdolitsky ; build all of the images with the new and the old, and then do a file by file comparison. Still on my list.

**Comment by deitch** [comment]
Ah, `Chown()` in memfs never was properly implemented. Going to patch it in.
