### ISSUE TITLE
FDB format error for lib64 packages

### ISSUE THREAD

**Issue by found-it** [chainguard-dev/apko#570]
I believe this is related to #566 but since that issue was reopened to discuss scripts I'm going to file a new issue.

## Issue 1 - Formatting error

I tried running `apk update` on the latest (at the time of writing) SDK image

```sh
docker run --pull always --rm --entrypoint apk ghcr.io/wolfi-dev/sdk@sha256:682995da244452240048b6fef907d014a8b9252550ca514871eb206cfa4cc701  update
```

Which results in an FDB format error

```
ERROR: FDB format error (line 8369, entry 'R')
ERROR: Unable to read database state: database file format error
ERROR: Failed to open apk database: database file format error
```

Inspecting `/lib/apk/db/installed` I can see the `nss-db` package

```
P:nss-db
V:2.37-r3
A:x86_64
L:GPL-3.0-or-later
T:NSS module for database lookups
o:glibc
m:
U:
D:so:ld-linux-x86-64.so.2 so:libc.so.6
p:cmd:makedb=2.37-r3 so:libnss_db.so.2=2
c:90bceb46bac6a4ec279418565fe539fff80441fc
i:[]
t:-62135596800
S:22092
I:107643
k:0
C:Q1Y1Vmv0/F5w/lPET8v11/CfTLEDc=
R:libnss_db.so.2
a:0:0:0755
Z:Q12vwQGEf+jMidejRaFpvnNQ8x+3Y=
F:usr
F:usr/bin
R:makedb
a:0:0:0755
Z:Q1iB3ld6p7pttCPD+Ml3nOPowXwR8=
F:var
F:var/db
R:Makefile
Z:Q1wSM7Ks8LLAvfRFI6dnRT8OVPUdU=
F:var/lib
F:var/lib/db
F:var/lib/db/sbom
R:nss-db-2.37-r3.spdx.json
Z:Q1k6Et9lpePsOmH6tYS6qJ/1k4dwA=
```

Specifically it's failing on the `R:libnss_db.so.2` line. Searching for that file I can see it in `/lib`

```sh
❯ find / -name libnss_db.so.2
/lib/libnss_db.so.2
```

From there I edited the `/lib/apk/db/installed` file and added

```
...
F:lib
R:libnss_db.so.2
```

**Note:** It's also failing for `nss-hesiod` and I did the same for that package

Once I added the `F:lib` line I was able to run `apk update` and install packages without issue. 

## Issue 2 - other /lib files not classified correctly
Taking a look at glibc I can see that `nss-db` is put into `/lib64` ([link](https://github.com/wolfi-dev/os/blob/22179717ea5df3bb84e2f77f7ef4bcb7a6a432d5/glibc.yaml#L392)) so I suspect it has something to do with `/lib64` being a symlink?

This is speculation so please correct me if I'm wrong, but it seems some other packages are also incorrectly misconfigured when they have files in `/lib`

For example in the `glibc` entry in `/lib/apk/db/installed` we can see the `libanl.so.1` file

```
P:glibc
V:2.37-r3
A:x86_64
L:GPL-3.0-or-later
T:the GNU C library
o:glibc
m:
U:
D:!musl wolfi-baselayout
p:cmd:ldconfig=2.37-r3 so:ld-linux-x86-64.so.2=2 so:libBrokenLocale.so.1=1 so:libanl.so.1=1 so:libc.so.6=6 so:libc_malloc_debug.so.0=0 so:libcrypt.so.1=1 so:libdl.so.2=2 so:libm.so.6=6 so:libmvec.so.1=1 so:libnsl.so.1=1 so:libnss_compat
.so.2=2 so:libnss_dns.so.2=2 so:libnss_files.so.2=2 so:libpthread.so.0=0 so:libresolv.so.2=2 so:librt.so.1=1 so:libthread_db.so.1=1 so:libutil.so.1=1
c:90bceb46bac6a4ec279418565fe539fff80441fc
i:[]
t:-62135596800
S:2594587
I:5455388
k:0
C:Q1pTM35JVs9y0cj1o0H8yGyr7ggGY=
F:etc
R:ld.so.conf
Z:Q11VhjuYYcqng196eHi2SGUlQzFtw=
R:rpc
Z:Q1jGjIKDdX2z6RCGWyRQdzh/kWagg=
R:ld-linux-x86-64.so.2
a:0:0:0755
Z:Q1rAHY7Fwr25zWIWxfcs1sqKqsVXc=
R:libBrokenLocale.so.1
a:0:0:0755
Z:Q1MnsBeLXtbe5tGZipuWIfoIu/HE4=
R:libanl.so.1
```

It seems to me that this package entry is implying that `libanl.so.1` is in `/etc` (please correct me if I'm wrong, I'm still coming up to speed on apk packaging). However searching for the file indicates it's in `/lib`

```sh
❯ find / -name libanl.so.1
/lib/libanl.so.1
```

I wanted to call this out since if it is an issue it seems related, and it results in a silent failure. The `installed` file is all formatted correctly but it might be looking for certain files in the wrong directories.

## Some evidence

I tried adding this right before [this line](https://github.com/chainguard-dev/apko/blob/c0407cc27459800e696bf4a85b8748f40370cf46/pkg/apk/impl/installed.go#L77)
```go
            if strings.Contains(f.Name, "lib64/") {
                pkgLines = append(pkgLines, fmt.Sprintf("F:%s", "lib"))
            }
```

And it created an installed db that was formatted correctly on the first try. It seems that the current processing is improperly writing the package entries for files in `/lib64`.

Happy to keep taking a look but wanted to make sure this was tracked for others to look at as well.

**Comment by found-it** [comment]
I'm wondering if it's some weirdness with how the apk gzip is expanded. When the apk's are installed it seems that the list of tarball headers we're processing doesn't contain a `/lib64` entry and instead just contains `/lib64/libnss_db.so.2` or for the case of `glibc` `/lib64/linanl.so.1`. So the way we are processing things right now, it never see's a tar header for `lib64` so it never writes an `F:` entry. Instead it just processes `/lib64/libnss_db.so.2` as a regular file and moves on

**Comment by deitch** [comment]
Got it!
