### ISSUE TITLE
apko is missing some version information

### ISSUE THREAD

**Issue by deitch** [chainguard-dev/apko#591]
Run this following:

```$ docker run -it --rm cgr.dev/chainguard/apko:latest-20230322  version
     _      ____    _  __   ___
    / \    |  _ \  | |/ /  / _ \
   / _ \   | |_) | | ' /  | | | |
  / ___ \  |  __/  | . \  | |_| |
 /_/   \_\ |_|     |_|\_\  \___/
apko

GitVersion:    v0.7.1
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
GoVersion:     go1.20.1
Compiler:      gc
Platform:      linux/arm64
```

The commit, tree state and build date are missing, which makes resolving issues a bit of guesswork to know what version someone is on.

When I run `make apko`, it does do the right thing:

```$ ./apko
     _      ____    _  __   ___
    / \    |  _ \  | |/ /  / _ \
   / _ \   | |_) | | ' /  | | | |
  / ___ \  |  __/  | . \  | |_| |
 /_/   \_\ |_|     |_|\_\  \___/
apko

GitVersion:    v0.7.2-11-gfab93a1
GitCommit:     fab93a165dcd81b06923a3dd6943a88223c19407
GitTreeState:  clean
BuildDate:     '2023-03-21T15:46:39Z'
GoVersion:     go1.20.1
Compiler:      gc
Platform:      darwin/arm64
```

So it has something to do with how it gets build for publishing in the release pipeline. I couldn't quite figure out where that is.

I think it has something to do with [this in release.yaml](https://github.com/chainguard-dev/apko/blob/35d290f3703a4201def88713600b4461be029b30/.github/workflows/release.yaml#L77-L84):

```yaml
    - name: Publish/Sign apko image
      run: |
        # If not a tagged release, override image tag to "canary"
        export IMAGE_TAG=${GITHUB_REF#refs/tags/}
        if [[ $GITHUB_REF != refs/tags/* ]]; then
          export IMAGE_TAG=canary
        fi
        make sign-image
```

**Comment by imjasonh** [comment]
This is probably due to how the apko apk is built in Wolfi: https://github.com/wolfi-dev/os/blob/main/apko.yaml

**Comment by deitch** [comment]
I was wondering why I could not find it in the pipelines in this repo. That explains it. 😄 

The `make apko` target does the right thing with `-X` flags. Is there a way to use that instead? I don't quite know how to modify it.

**Comment by kaniini** [comment]
Wolfi only ships the apko *releases*.  We provide `ghcr.io/wolfi-dev/sdk:latest` image for operational purposes.

**Comment by deitch** [comment]
@kaniini but we do still publish `cgr.dev/chainguard/apko`; should we not include the build information in them? We already have the semver and go ver; might as well get the rest?

**Comment by deitch** [comment]
Makes sense. I will file it.

**Comment by deitch** [comment]
Is it under [[https://github.com/wolfi-dev/os/issues](https://github.com/wolfi-dev/os/issues/new/choose)? That only gives the option for new package request or security vulnerability.

**Comment by kaniini** [comment]
Just click other.  We will add package defect form.
