### ISSUE TITLE
Problems with python finding itself

### ISSUE THREAD

**Issue by luhring** [chainguard-dev/apko#627]
Opening for @deitch  (feel free to retitle and/or correct the below!)

When debugging failing E2E tests in Melange (e.g. https://github.com/chainguard-dev/melange/actions/runs/4743961439/jobs/8424331419?pr=395) we noticed two issues:

1. the apk implementation doesn't have support for using tilde (`~`) to specify a version for a dependency
2. the apk implementation doesn't have support a package depending directly on itself (i.e. not on a provides, but the package itself) — e.g. `python3` depending on `python3~3.11`

**Comment by luhring** [comment]
@kaniini Any ideas about why Melange's E2E tests weren't failing before now? Could it be that the outside world change (e.g. Alpine's config for `python3`?)

**Comment by jdolitsky** [comment]
FWIW I also have problems finding myself

**Comment by kaniini** [comment]
I suspect that python 3.11.3 having that dependency is just a side effect of https://github.com/alpinelinux/abuild/commit/6806a0d39b25c30ca7368b29a9ff78c57c0deec9

**Comment by deitch** [comment]
The first part (tilde support) is in #630, but I am a little concerned about the second part.

apko already has support for "I depend on `foo`, my package provides `foo`, I satisfy my own requirement." This would expand it to include, "I depend on `foo=3.11`, I _am_ `foo=3.11`, I satisfy my own requirement.

We can do that, and add tests, without too much pain.

But then what happens with the wolfi build dependencies? The issue discussed [here](https://github.com/wolfi-dev/os/pull/1480) means that it expects, "if I depend on my own name, do _not_ satisfy it myself, rather look for a different (possibly lower) version to find that." In the wolfi case, that means potentially stage3.

We do not (yet) use the same code for resolving the build graph in wolfictl and apko, but we are working to get there, and the logic should be the same.

Can a package A itself resolve a dependency on package A (what this suggests), or can it not (what the wolfi-dev/os issue suggest)?

**Comment by kaniini** [comment]
> Can a package A itself resolve a dependency on package A (what this suggests)

Yes.  It has to be this way.

The `-stage0` stuff in Wolfi is a policy decision that does not imply any behavioral requirement of the solver.

**Comment by deitch** [comment]
So the normal apk resolution graph says, "A-2.0 depends on A can be satisfied by itself." We took a decision that says, "no, it cannot".

That can be satisfied with options. Cool, thanks.

**Comment by deitch** [comment]
@luhring see #631
