### ISSUE TITLE
Solver does not consider provided package version in provides entries

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/apko#632]
Consider the following repository:

- `a-1-r0`
- `b-2-r0`, provides `a=0.9`

If a user requests package `a`, `b` will be selected instead of `a` as it provides `a` (at version `0.9`) but has a higher package version (`2`).  Instead, `a` should be selected as it provides `a` at version `1`.

**Comment by deitch** [comment]
You have the problem identified correctly, and I have added a test to check for it. It uses both name and provides to look up all packages that satisfy `a`. In doing so, it finds both `a-1` and `b-2`. It then sorts them in descending order of preference and returns them.

The sort algorithm, however, looks at the _package_ version, and not the _provides_ version. Hence the issue.
