### ISSUE TITLE
Question: Install specific package version 

### ISSUE THREAD

**Issue by MathKlim** [chainguard-dev/apko#704]
Hi,

I just discovered your work and it's awesome ! 

I have one question : is it possible to install a specific version of an apk package ? 

I have successfully built a container with apko containing terraform, terragrunt, and terratag (had to use melange for this one, but worked like a charm).  Usually what I do in Dockerfiles is that I pin down the version of the soft I use, for example : 

```dockerfile
ARG TERRAFORM_VERSION=1.3.7

ENV TERRAFORM_URL https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# download terraform
RUN wget "$TERRAFORM_URL" \
  && unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin/ \
  && chmod +x /usr/bin/terraform \
  && terraform --version
```

This way I'm sure of the version installed.

Is there a similar thing with apko ? If not, is it in the roadmap ? Should I do it myself with melange ?

**Comment by patrickpichler** [comment]
Hey :slightly_smiling_face: 

I had the same problem so I ventured into the source code of apko to figure this out. Apkos underlying apk implementation ([go-apk](https://github.com/chainguard-dev/go-apk)) also implements support for alpines version constraints. This mean you can fix a version by providing a package name like `kyverno-cli=1.9.2`. 

I hope this helps :slightly_smiling_face:

**Comment by amouat** [comment]
Thanks @patrickpichler. We should document this better.

@erikaheidi is this in the apko docs at all?

@MathKlim did you get this working - are you happy for us to close now?

**Comment by MathKlim** [comment]
@amouat Yes, that's ok, you can close it now.

Thanks
