### ISSUE TITLE
InstallLdconfigLinks appears to be a no-op

### ISSUE THREAD

**Issue by jonjohnsonjr** [chainguard-dev/apko#765]
We call `ldconfig(fsys, "/lib")`: https://github.com/chainguard-dev/apko/blob/e6788cf5bbf7a075e21a2a69477c96999df4dd30/pkg/build/ldconfig.go#L105

Which means at this point, `libdir` will be `"/lib"`: https://github.com/chainguard-dev/apko/blob/e6788cf5bbf7a075e21a2a69477c96999df4dd30/pkg/build/ldconfig.go#L51-L53

Which means we always hit that `continue`.

The only places that actually modify the `links` map come after that `continue`:

https://github.com/chainguard-dev/apko/blob/e6788cf5bbf7a075e21a2a69477c96999df4dd30/pkg/build/ldconfig.go#L61
https://github.com/chainguard-dev/apko/blob/e6788cf5bbf7a075e21a2a69477c96999df4dd30/pkg/build/ldconfig.go#L75

So we always return an empty map, which means `InstallLdconfigLinks` iterates over an empty map and does nothing: https://github.com/chainguard-dev/apko/blob/e6788cf5bbf7a075e21a2a69477c96999df4dd30/pkg/build/ldconfig.go#L105-L118

Is that intentional?

**Comment by deitch** [comment]
I honestly do not know. I remember now going through this, and basically implementing what is in https://git.alpinelinux.org/aports/tree/main/musl/ldconfig . But does that change anything?

**Comment by jonjohnsonjr** [comment]
I think I understand this now, let me summarize for a future version of myself:

This exists to workaround lack of postinstall scripts (as does `InstallBusyboxLinks`, FWIW).

Looking at the `scripts.tar` in our favorite image, at the `glibc-2.37-r6.Q1WTZZn8DDEiZzGig4nWfTgHYB9RE=.trigger` file:

```
crane blob cgr.dev/chainguard/ko@sha256:fdd2d5343f9653720379ca6026fee59a7a896fef517de151de7413e1c6e85b5b \
  | tar -Oxz lib/apk/db/scripts.tar \
  | tar -Ox glibc-2.37-r6.Q1WTZZn8DDEiZzGig4nWfTgHYB9RE=.trigger
```

We get:

```sh
#!/bin/busybox sh
/sbin/ldconfig
```

The [ldconfig](https://git.alpinelinux.org/aports/tree/main/musl/ldconfig) impl:

```sh
#!/bin/sh
scan_dirs() {
	scanelf -qS "$@" | while read SONAME FILE; do
		TARGET="${FILE##*/}"
		LINK="${FILE%/*}/$SONAME"
		case "$FILE" in
		/lib/*|/usr/lib/*|/usr/local/lib/*) ;;
		*) [ -h "$LINK" -o ! -e "$LINK" ] && ln -sf "$TARGET" "$LINK"
		esac
	done
	return 0
}
# eat ldconfig options
while getopts "nNvXvf:C:r:" opt; do
	:
done
shift $(( $OPTIND - 1 ))
[ $# -gt 0 ] && scan_dirs "$@"
```

This calls `scan_dirs`, which calls`scanelf --quiet --soname "$@"`. We pass no arguments, so what does `scanelf` do with no arguments?

Per https://wiki.gentoo.org/wiki/Hardened/PaX_Utilities#Using_scanelf_for_text_relocations

> The following example will search library paths recursively, without leaving the mounted file system and ignoring symbolic links, for any ELF binary containing a text relocation:
> ```sh
> root #scanelf -lqtmyR
> ```

So we are only looking in `/lib`, which means this _is_ a no-op, but the equivalent of `/sbin/ldconfig` would be looking at _every_ file in the filesystem, not just `/lib`, so I think this is a bug in apko.

Do we care? Is there an easy way to confirm that these links are missing?

Perhaps because wolfi doesn't rely on this behavior, we don't see it, but this could be broken for apko when used with other APKs?

**Comment by kaniini** [comment]
musl does not care at all about ldconfig.  I think we can delete this functionality.

**Comment by deitch** [comment]
But don't we use glibc?
