### ISSUE TITLE
Missing install instruction

### ISSUE THREAD

**Issue by sfermigier** [chainguard-dev/apko#77]
Not a Go developer here: I have no idea how to build / install the software.

`make` fails with the message:

```
/bin/sh: goimports: command not found
/bin/sh: ko: command not found
mkdir -p /tmp/ko
Image Digest
```

**Comment by kruskall** [comment]
@sfermigier :wave: 

There's a `apko` task here: https://github.com/chainguard-dev/apko/blob/main/Makefile#L82

You should run `make apko`

**Comment by kaniini** [comment]
You might also look at https://git.alpinelinux.org/aports/tree/testing/apko/APKBUILD

**Comment by panekj** [comment]
with `apk` you can run `apk add -X https://dl-cdn.alpinelinux.org/alpine/edge/testing/ apko`

@kaniini would it be okay to make `help` target the default one for make and add short help description for `apko`/`install` like other targets have?

**Comment by kaniini** [comment]
@panekj yes, feel free to refactor the makefile, though i just made the default target the `apko` one :)
