### ISSUE TITLE
`apko-publish` doesn't copy SBOM to local `sbomPath`

### ISSUE THREAD

**Issue by andros21** [chainguard-dev/apko#804]
During the usage of [`apko-snapshot`](https://github.com/chainguard-images/actions/tree/main/apko-snapshot) action I experienced a problem at SBOM attestation step:

```console
...
Run function attest_sbom {
Unable to find SBOM on disk: sbom-index.spdx.json (arch: index). Exiting.
Error: Process completed with exit code 1.
```
I've reproduced it tweaking [`test-scan-apk.yaml`](https://github.com/andros21/actions/commit/df845b4a0bfe046d933ec6f71c5a529f75d0457e) workflow, [here its run with full logs](https://github.com/andros21/actions/actions/runs/5517957909).

It seems that since `apko` started to generate also SBOM in tempdir `apko-*`, SBOM are correctly copied in the requested `sbomPath` when using `apko-build`, thanks to this snip of code:

https://github.com/chainguard-dev/apko/blob/37b82f3a5bd85bde214df382fa974bc8dc88f692/internal/cli/build.go#L164-L170

but not when using `apko-publish`, I was wondering if this is the wanted behavior.
Thanks

**Comment by joemiller** [comment]
I noticed this as well. I think it was lost in the publish cmd refactor between 0.8.0 and 0.9.0. It looks like this was probably the code that wrote them to the specified path during `publish` previously https://github.com/chainguard-dev/apko/blob/v0.8.0/internal/cli/publish.go#L316-L363 .. If the flag was set the code would use the specified path, else it would use a tempdir
