### ISSUE TITLE
Question: apko should be support copy files?

### ISSUE THREAD

**Issue by lpcalisi** [chainguard-dev/apko#852]
*apko* have the chance to copy some files? or execute something?

apko is great to gen base images, but is common require that this bases images need some configuration file or script and they are copied in base image in order to abstrac final application images (or images uses for build). Does it make sense? Or we should make this inside of a build system?

**Comment by lpcalisi** [comment]
@jonjohnsonjr @rawlingsj @kaniini

**Comment by tuananh** [comment]
the current approach to package them into apk package like this i think https://github.com/wolfi-dev/os/blob/main/container-entrypoint.yaml

**Comment by jpolania** [comment]
Having support to copy files (which can be anything from binaries, config file, execution code, etc)

If apko whats to be better than Dockerfile ... then I'd suggest have either apko or melange support COPY files/folder funtionality

**Comment by kaniini** [comment]
Yes, you can copy files into an apk with melange.  It’s already supported.

**Comment by jpolania** [comment]
Just to clarify on this issue.  Apko doesn't support copy files and seems to be is the architecture design

If you want to use the copy file function in **melange** here is a basic example

Imagine you have a file called `mycode.sh` and you want that file inside your apk image via melange. You need to copy from BUILD_DIR to ${{targets.destdir}}

Example of melange pipeline section

`
pipeline:
  - runs: |
      BUILD_DIR="/home/build"
      cp "${BUILD_DIR}/mycode.sh" "${{targets.destdir}}/mycode.sh"
      ...
      ...
` 

Hope that helps to everyone who read this post

**Comment by tuananh** [comment]
i have an example (template) here how to package file with melange and then use that package in apko.

https://github.com/tuananh/apko-image-template
