### ISSUE TITLE
Build OCI image without signing the APK package

### ISSUE THREAD

**Issue by ma-ble** [chainguard-dev/apko#888]
Hello, 

I'm currently trying to run the [nginx-image-demo](https://github.com/chainguard-dev/nginx-image-demo/tree/main) locally. 
When building the oci image I get an error message that the package needs to be signed.

apko vrsion: 0.10.0
melange version: 0.4.0

```
$ melange build .melange.yaml --arch x86_64
$ apko build .apko.yaml nginx:test nginx.tar --debug --arch x86_64

Error: failed to build layer image for "amd64": installing apk packages: error getting package dependencies: error getting repository indexes: failed to find key name in signature file name: APKINDEX
```

The error says that you should create a signature for APKINDEX.

The documentation from [melage ](https://edu.chainguard.dev/open-source/melange/faq/)and [apko ](https://edu.chainguard.dev/open-source/apko/faq/)states that signing the packages is not necessary.

Is there a way that I can build the oci image without signing the package?

**Comment by slimm609** [comment]
it looks like go-apk library supports `ignoreSignatures` in ResolveWorld but there is no option to pass this currently for local context. This would be great to support though and local signing and verification in the same pipeline provides little benefit.
