### ISSUE TITLE
About the release scheme

### ISSUE THREAD

**Issue by chenrui333** [chainguard-dev/apko#936]
👋 It looks like all the releases are marked pre-release, is there any docs for it? It would be good that the releases are marked as stable release, so that pre-release label can be used for pre-release purposes. Thanks!

 (side note, we, homebrew, are using the release API to distinguish the stable release vs pre-release)

relates to https://github.com/Homebrew/homebrew-core/pull/152553

**Comment by imjasonh** [comment]
Hey thanks for reaching out.

I think we should list all releases as not-pre-release (i.e., production ready) since we ourselves use apko heavily in production.

I'll take a stab at documenting the release process better so we remember to do this.

**Comment by chenrui333** [comment]
@imjasonh thanks! I think I am all set now.
